
shiro:
  realms:
    - users:
        adminuser: "password, admin, user"
        user: "password, user"
      roles:
        admin: "admin"

shiroweb:
  urls:
    "/private" : perms[admin]
    "/pub"   : anon