shiro:
  realms:
    - users:
        user1: "password, user"
        user2: "password, user, admin"

shiroweb:
  urls:
    "/public" : anon
    "/private" : "noSessionCreation, authcBasic, roles[user]"